import Navbar from '@/component/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import Header from '@/component/header/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      
      <div className="max-w-1xl mx-auto p-3">
      <Header/>
      <div className='max-w-3xl mx-auto p-4'>
      <Navbar/>
      
      <div className="mt-8">{children}</div>
      
      </div>
      </div>
      </body>
    </html>
  )
}
